### ISSUE TITLE
Typo in readme.md

### ISSUE THREAD

**Issue by akshay-js** [LoginRadius/php-sdk#16]
Typo in readme.md

**Comment by 23krishna** [comment]
I can help please assign me the task

**Comment by S1SYPHOS** [comment]
Oh how badly people want stuff for `Hacktoberfest` .. :fox_face:

**Comment by tb-rules10** [comment]
Merge #25  (Corrected Spelling Mistake)

**Comment by giriraj12000** [comment]
Hi,

It seems this PR is not eligible for hacktoberfest so closing this issue.

Thanks
