### ISSUE TITLE
UserAPI - Missing Endpoint

### ISSUE THREAD

**Issue by lo3ty** [LoginRadius/php-sdk#3]
Hi there,

The API clearly states that there is a Endpoint for fetching a User Profile by providing an access-token.
http://apidocs.loginradius.com/docs/user-profile-by-access-token

In the master-dev Release of this PHP SDK this Endpoint is not implemented.
Any particular reason for that or did you forgot about this?

In some cases, such endpoint would be quite handy...

Leonhard

**Comment by Karl-LoginRadius** [comment]
Hi,

We have this api already integrated in SocialLoginAPI object. You can check the getUserProfiledata method.

If you have further questions regarding the API or LoginRadius you can open a support ticket via our ticketing system . 
Thanks,
