### ISSUE TITLE
Exceptions in PHP SDK

### ISSUE THREAD

**Issue by LC43** [LoginRadius/php-sdk#8]
Hi,

What's the point of wrapping the calls with try catch the exceptions, if the apiClient always returns a value, and never, ever, an LoginRadiusException?

https://github.com/LoginRadius/php-sdk/blob/master/src/LoginRadiusSDK/Utility/Functions.php#L149

**Comment by Agarwal-Sudhanshu** [comment]
Hi Pedro,

The idea behind wrapping the calls with try-catch is to handle exceptions e.g.

- API Key & API Secret is not configured
- `cURL`  library is not installed
- `allow_url_fopen` is not enabled
- LoginRadius API returned `ErrorCode`

Hope this will help.
